
//------- ------------------burger related actions ------------------
export const CHANGE_INGREDIENT_NO='CHANGE_INGREDIENT_NO'
export const SET_INGREDIENTS_ORDER='SET_INGREDIENTS_ORDER'
export const FETCH_INGREDIENTS_SUCCESS='FETCH_INGREDIENTS_SUCCESS'
export const FETCH_INGREDIENTS_FAILED='FETCH_INGREDIENTS_FAILED'
export const FETCH_INGREDIENTS_START='FETCH_INGREDIENTS_START'
export const RESET_PRICE='RESET_PRICE'


// -------------------placing order and fetching order related actions---------------------
export const PLACE_ORDER_INIT='PLACE_ORDER_INIT'
export const PLACE_ORDER_START='PLACE_ORDER_START'
export const PLACE_ORDER_SUCCESS='PLACE_ORDER_SUCCESS'
export const PLACE_ORDER_FAILED='PLACE_ORDER_FAILED'
export const FETCH_ORDER_INIT='FETCH_ORDER_INIT'
export const FETCH_ORDER_START='FETCH_ORDER_START'
export const FETCH_ORDER_SUCCESSS='FETCH_ORDER_SUCCESSS'
export const FETCH_ORDER_FAILED='FETCH_ORDER_FAILED'
export const ERROR_NOTICED='ERROR_NOTICED'
export const PURCHASE_INIT='PURCHASE_INIT'


//------------ HANDLING AUTHENTICATION RELATED ACTIONS-------------------
export const AUTH_START='AUTH_START'
export const AUTH_REQ_START='AUTH_REQ_START'
export const AUTH_SUCCESS='AUTH_SUCCESS'
export const AUTH_FAILED='AUTH_FAILED'
export const AUTH_LOGOUT="AUTH_LOGOUT"
export const AUTH_LOGOUT_START='AUTH_LOGOUT_START'
export const CLEAR_SESSION_STORAGE='CLEAR_SESSION_STORAGE'
export const AUTH_AUTO_SIGN_IN="AUTH_AUTO_SIGN_IN"

